-- DELETE BACKUP TABLE IF EXISTS
-- USE DBMS_COURSE;
-- DROP TABLE IF EXISTS BACKUP_USERS;

-- COPY STUDENT_FEE TABLE TO BACKUP_USER TABLE (DATA AND SCHEMA BOTH)
-- CREATE TABLE BACKUP_USERS
-- SELECT * FROM STUDENT_FEE 

-- COPY STUDENT_FEE TABLE TO BACKUP_USER (ONLY SCHEMA)
-- CREATE TABLE BACKUP_USERS
-- LIKE STUDENT_FEE;

-- CREATE A TRIGGER TO SAVE DELETED DATA IN BACKUP_USERS TABLE

DELIMITER |

CREATE TRIGGER backup_trigger
AFTER DELETE ON STUDENT_FEE

FOR EACH ROW
BEGIN
	INSERT INTO backup_users(NAME)
    VALUES(OLD.NAME);
END|